### PR TITLE
Fiddling

### PR DESCRIPTION
**Pull request by James88g**
$ git checkout -b featurename

### CODE REVIEW

**Review by James88g — COMMENTED** [review]
$ git checkout -b featurename

**Comment by James88g** [comment]
Gp

**Comment by kaizushi** [comment]
Feel free to change fiddling. None of this works or is ready for master, which is intended to be bug free and functional.

**Comment by James88g** [comment]
I'm not really good with computers

Hello , my name is Dane it's nice to meet you , I live in new Zealand but was overseas for many years , I've come back home , to be honest I'm in the business of selling drugs here in New Zealand , the markets... Fucking clone profiles rinse and repeat same bullshit vendors probably just a couple of people at the top pulling the strings , blackscale , blackship thesaltonthesea , crystalcleer/krybaby/priority mail the list goes on that 9k fuckwit on dread meth forum mod... They ripped me off , i don't mind to much maybe lost 40k I'll make it back , anyway I need your help , I need decent vendors I need to improve my opsec , I know nothing about cyber security im just a drug dealer/head chef at a restaurant / family man and dog lover , I need help with my systems I need decent vendors and I need to stop them doing what they are doing , I'm annoyed if someone did that to me here... We are both vendors , my mums parents are Jews holocaust survivors I've seen suffering and hell when I was overseas , I'm loyal honest and pay a good price , I'm was wronged I need help to ensure others aren't also wronged I have resources at my disposal they might be of use to you obviously I will pay you in addition to providing resources to you , mygithub is James88g , thanks for your consideration for my request Dane :)
Sent from ProtonMail mobile

Sent from ProtonMail mobile

-------- Original Message --------

**Pull request closed without merging**
